"""add chunk embeddings

Revision ID: 7aa932b3ed35
Revises: 98f596f42dfd
Create Date: 2026-09-28 21:34:53.554735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7aa932b3ed35'
down_revision: Union[str, Sequence[str], None] = '98f596f42dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('content_hash', sa.Text(), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding', Vector(384), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_model', sa.Text(), nullable=True))
    op.create_index(op.f('ix_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_content_hash'), table_name='document_chunks')
    op.drop_column('document_chunks', 'embedding_model')
    op.drop_column('document_chunks', 'embedding')
    op.drop_column('document_chunks', 'content_hash')
    # ### end Alembic commands ###
