"""ensure unique document chunk indexes

Revision ID: 98f596f42dfd
Revises: 8ccf47c92cae
Create Date: 2026-09-27 14:42:02.331216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f596f42dfd'
down_revision: Union[str, Sequence[str], None] = '8ccf47c92cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_chunk_index', 'document_chunks', ['document_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_chunk_index', 'document_chunks', type_='unique')
    # ### end Alembic commands ###
