"""add regulatory updates

Revision ID: a7b9f494cfc3
Revises: 7aa932b3ed35
Create Date: 2026-10-08 11:53:49.847479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b9f494cfc3'
down_revision: Union[str, Sequence[str], None] = '7aa932b3ed35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('importance', sa.String(length=50), nullable=True),
    sa.Column('simplification', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_updates_document_id'), 'regulatory_updates', ['document_id'], unique=True)
    op.create_index(op.f('ix_regulatory_updates_id'), 'regulatory_updates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulatory_updates_id'), table_name='regulatory_updates')
    op.drop_index(op.f('ix_regulatory_updates_document_id'), table_name='regulatory_updates')
    op.drop_table('regulatory_updates')
    # ### end Alembic commands ###
